package com.ez.myblogsbackend.entity;

import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import javax.persistence.*;
import javax.validation.constraints.Min;
import javax.validation.constraints.Size;
import java.util.Date;

@AllArgsConstructor
@NoArgsConstructor
@ToString
@Getter
@Setter
@Entity
@Table(name = "comment")
public class Comment {

    @Min(value = 1, message = "Value of post id must be greater than or equal to 1")
    private Long postid;

    @Id
    // GenerationType.IDENTITY: id is generated by mySQL
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long commentid;

    // comment content
    @Size(min = 1, message = "Please input a description")
    private String commentDescription;

    @Min(value = 1, message = "Value of commenter id must be greater than or equal to 1")
    private long commenterid;

    // comment is created on this datetime.
    // annotaion @CreationTimestamp: will auto save current datetime to this field in database
    @CreationTimestamp
    private Date commentDatetime;

    // do not need includes 2 fields: commentid and commentDatetime.
    // because these 2 fields will auto save into database.
    public Comment(Long postid, String commentDescription, long commenterid) {

        this.postid = postid;
        this.commentDescription = commentDescription;
        this.commenterid = commenterid;

    }
}
